# Generated by Django 3.2.8 on 2021-10-23 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20211022_1403'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-publish', 'title'], 'verbose_name': 'post', 'verbose_name_plural': 'posts'},
        ),
    ]
